### ISSUE TITLE
[Quests] Add completed quests to MyMeta profile

### ISSUE THREAD

**Issue by vidvidvid** [MetaFam/TheGame#1025]
### What would you like to be added?

MyMeta profile should have a section which displays a list of all accepted quests.
A particular quest list item should include:
- title that links to the quest UI
- link to the proof of completion

### Todo

- [ ] make whole quest cards clickable (or just their headers)
- [x] figure out populating the `quest_completions` results with quest data
- [x] link the quests from profile section to their view
- [x] make the section pretty
- [x] make the `display all` modal

### Ideas

- xp rewarded

### Why is this needed?

Questing MVP https://miro.com/app/board/o9J_ldTAEnQ=/
