### ISSUE TITLE
Merge `develop` to `master` on 2022/3/1

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1146]
To make our plethora of new features available to the deserving public, we need to merge the `develop` branch into `master`. There are a few outstanding issues to complete before that is a responsible thing to do.

* [x] #1114 will prevent some users from being able to log into the site & needs to be fixed.
* [x] #1096: When linking new users to the site, the `/me` path drops them directly into their profile. It's broke.
* [x] #1102: A determination needs to be made if the OpenSea API can be fixed &, if not, the NFTs portion of the profile should be hidden.
* [x] #1124: The optimistic updates of a player's profile when they make edits should be completed & thoroughly tested.
* [x] #1127: The optimistic updates of a player's profile when they make edits should be completed & thoroughly tested.
* [x] #1047: An updated landing page is in the works including a 3D animation. If possible, this should be included.
   * [x] by including #1047 we also need to include the fix for #1128 
* [x] #1131: A page giving details about SEEDs is in the works and scheduled to make it in.

**Comment by dysbulic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaOS-6012e782d1bec10015d7f4e5/issues/MetaFam/TheGame/1146?planning-poker) with ZenHub @alalonde @mquellhorst @vidvidvid @dan13ram

**Comment by vidvidvid** [comment]
@dysbulic @alalonde can you run `npm run release -- --release-as 0.2.0` to create a changelog of the updates since the `0.1.0` it was run once you merge to master?

**Comment by dysbulic** [comment]
I'm collecting issues as I wrap up the final hours before the third deadline passes. This one I think I'll make…

*(In my defense, I've been working on the profile editing stuff for almost two months, but I'd only been using the editing forms on the details page. Adapting the interfaces to support the profile editing wizard took up a large chunk of my time & is what I misestimated the worst.)*

The current known issues are:
* [ ] it isn't possible to change the images in a player's profile
* [ ] the "Player Type" box isn't populating with a value when inserted into a profile
* [ ] the options in the selector for skills are too narrow and don't fill the dropdown
* [ ] the skills dropdown should be allowed to use more screen real estate when it opens *(maybe opening up rather than down when in a modal?)*
* [ ] the skills dropdown shouldn't close after each selection
* [ ] the roles options are a fixed width currently, and should narrow a bit if necessary to create three columns
* [ ] line breaks are preserved when the bio is displayed in the profile details page, but not for the player tiles
* [ ] the layout for the display of NFTs needs to be modeled after the layout used for DAOs
* [ ] the NFT list runs over the bottom of the modal containing it
* [ ] NFT names are being cropped by the edge of their containing box & should have `text-overflow: ellipsis` applied along with a `Tooltip` containing the full name

Various profile editing tests need to be performed with:
* [ ] an existing user with a profile
* [ ] a user without a profile in either Ceramic or MyMeta
* [ ] a user with a Ceramic profile, but not one on MyMeta *(this person runs the risk of overwriting their profile. @dan13ram's suggestion was to cache the profile during the `/auth-webhook` call where the entries in the `player` & `profile` tables are created. [`bottleneck`](//github.com/SGrondin/bottleneck#readme) has priority levels for tasks, so this is feasible.)*
* [ ] a user on a mobile device

**Comment by vidvidvid** [comment]
need to fix this as well:

- [ ] #1168

**Comment by dysbulic** [comment]
> need to fix [#1168] as well

@vidvidvid, my goal is to hit a code freeze at noon. I've got the stuff above & a couple other issues & I don't know that I'll have time.

You're more than welcome to commit to this branch directly though. I'm 98% working on profile stuff, so we shouldn't step on each other's toes.

**Comment by vidvidvid** [comment]
@dysbulic awesome, will add to it then.

**Comment by dysbulic** [comment]
So, this, apparently, didn't go correctly and a newly created PR from `develop` to `master` (#1189) reports 400+ files changed with commits dating back months…
