### ISSUE TITLE
Questing system overview

### ISSUE THREAD

**Issue by vidvidvid** [MetaFam/TheGame#1177]
### Dashboard

Overview of the categories of quests.
- [ ] #1150 
  - [ ] Borders/Portals
  - [ ] Completion/progress indicator
  - [x] Category descriptions
  - [x] #1182 

### Initiation Quests

- [ ] UI
- [x] Move quests to MetaOS
- [x] Quest descriptions
- [ ] Quest completions
  - [x] tick boxes
  - [ ] upload proof
  - [ ] save progress to the db

### Onboarding flow

- [ ] Add a link to quests from the ending page of the setup wizard

#### Web 3 Onboarding

**Comment by peth-yursick** [comment]
Looks like it was an extra issue (or just an issue & the other one was PR?), which was also closed
