### ISSUE TITLE
[Roadmap] MyMeta

### ISSUE THREAD

**Issue by geleeroyale** [MetaFam/TheGame#501]
Checklist:
- [ ] [**Move to Ceramic**](https://github.com/MetaFam/TheGame/issues/309) - Migrate from 3Box to IDX/Ceramic
- [ ] [**Role select**](https://github.com/MetaFam/TheGame/issues/311) - Allow players to choose basic roles when setting up their profiles so we can move the role select out of discord & change the onboarding flow to start with profile creation.
- [ ] [**New sections**](https://github.com/MetaFam/TheGame/issues/264) - "add new section" functionality implemented for people to be able to add things to their profiles.
- [ ] [**Contracting**](https://github.com/MetaFam/TheGame/issues/547) - Allow people to start contracts between each other.
- [x] [**xDAI & Polygon DAOs**](https://github.com/MetaFam/TheGame/issues/549) - Add support for xDAI & Polygon DAOs.
- [ ] [**xDAI & Polygon NFTs**](https://github.com/MetaFam/TheGame/issues/647) - Add support for xDAI & Polygon DAOs & NFTs.
- [ ] [**Moar Data! - Add more data points in MyMeta profiles by integrating data & stats from Gitcoin & other places like Discourse.**](https://github.com/MetaFam/TheGame/issues/757)
- [x] **[Magic color wheel](https://github.com/MetaFam/TheGame/issues/550)** - It has already been built, just need someone to adjust the styling to look as it was designed.
- [x] [**Filtering**](https://github.com/MetaFam/TheGame/issues/542) - Filtering functionality.
- [ ] **Gnosis Multisig as a guild** - Right now we have DAOHaus DAOs, maybe we should also add support for Gnosis multisigs
- [ ] [**Custom backgrounds**](https://github.com/MetaFam/TheGame/issues/443)
- [ ] **Custom colors**?

Definition: @peth-yursick 

Mockups: @peth-yursick

**Comment by peth-yursick** [comment]
Merged to MetaOS Full Roadmap #913
