### ISSUE TITLE
[Roadmap] Quests 

### ISSUE THREAD

**Issue by geleeroyale** [MetaFam/TheGame#505]
- [ ] **Quest completions via props channel** - Some quests are completed simply by doing them but others need to be accounted for through #did-a-thing or by adding initiatives. We need to figure out what this looks like. For smaller quests, the player could click "complete quest" & there could be a bot @player who completed the quest in a hidden #give-props channel where XP Fairies then verify & reward quest completions.
- [ ] **Quest filtering** - Quest filtering by role by default. Evergreen quests appearing separately from the rest & other ways of making it easier for people to choose among 100 quests.
- [ ] **[RAIDS](https://github.com/MetaFam/TheGame/issues/642)** - Raids are basically groups of quests. The raid description should look like the quest description except the bottom section would be a list of cards that represent separate quests that are a part of the raid.
- [ ] **[Onboarding quests](https://github.com/MetaFam/TheGame/issues/627)** - Right now all the quests are on Notion. We'll be moving all quests from the Quests board into the quests module on the website but the onboarding quests need a special place. People will need to "complete at least 5 onboarding quests before you can access the rest" or something like that.
- [ ] **Design update** - ninjafire said she wasn't done with the design but Paco had already moved forward & implemented it. We need to get someone from the designers guild to do another run through the design & see if/what things need to be improved.
- [ ] **Quest upvoting** - We got a shitton of quests but no way of ranking them by importance. We should build a system for upvoting them. Maybe something like "need to own 10pSeeds to be able to vote" & keep to that "1 player 1 vote" idea?
- [ ] **Services offered** - Like quests, but for listing services being offered by players & guilds.
- [ ] **Quests via issues**? - Similar to like on Gitcoin, except automated. In gitcoin, you paste a link to the issue & it displays everything from the issue as a bounty. We should make it so that all issues on TheGame repo appear as quests in the Quests module.
- [ ] **Quests via bot**? - Could be done through the above system with the existing "issuize" bot that turns discord messages into issues, but might be better to do it more directly. Similar to now, the bot would first need to check if the person has enough pSeeds.

Definition: @peth-yursick

Mockups: @peth-yursick

**Comment by peth-yursick** [comment]
Merged to MetaOS Full Roadmap #913
