### ISSUE TITLE
[Roadmap] MetaOS

### ISSUE THREAD

**Issue by geleeroyale** [MetaFam/TheGame#506]
- [ ] **[MetaMenu](https://github.com/MetaFam/TheGame/issues/641)** - The main thing will be to build the navigation bar that Davor is designing & making things open below it rather than in a new tab. Going from there, we should try to get all the other pieces under the same interface.
  - [ ] **Move the newsletter from substack** - Eg. the newsletter itself should be moved from substack into the website itself & transform into a blog.
  - [ ] **Integrate the wiki** - Should be opening inside the website
  - [ ] **[Playbooks](https://github.com/MetaFam/metagame-wiki/issues/257) & Great Houses** - The main two pieces from the wiki that need to be easier to interact. They should both probably be individual modules rather than part of the wiki & made so that the Playbooks can be upvoted/downvoted, commented on etc.
 - [ ] **Seed Market** - A page where people can get an overview of everything they can do. From buying & selling, to planting or spending. It could begin as a simple page displaying links to where to buy or sell, where to plant & how to spend for things like podcast shout-out.
  - [ ] **Show community events on homepage** - This obviously needs design more than other pieces as the homepage itself needs to be designed first. We could start by moving on with the [windows issue](https://github.com/MetaFam/TheGame/issues/269) & having a calendar block embedded in the homepage.
  - [ ] **Build the podcast page** - Currently being designed
- [ ] **[Dashboard](https://github.com/MetaFam/TheGame/issues/337)** - the home page for MetaOS 
- [ ] **Journal** - A log of quests, XP & personal notes
- [ ] **Build a new landing page** - Self explanatory & probably more important than a bunch of things from the above. We should strive to get it done by the end of Season2 or early next season.
- [ ] **Services Offered** - The flipside of the quests module; here, rather than people/guilds posting tasks they need done, they will be posting skills & services they offer.
- [ ] **[Make everything open inside](https://github.com/MetaFam/TheGame/issues/269)** - Currently, clicking links in the appdrawer/nav bar opens pages in new tabs. Instead, everything should be opening inside the page, below the navigation bar itself.
- [ ] **Thank you MetaGame (Testimonies)** - Just a page where people can thank MetaGame for what it helped them achieve. This will be a part of the new landing page but should probably also be a page of its own somewhere on the platform.
- [ ] **[Ticker Line](https://github.com/MetaFam/TheGame/issues/327)** - For displaying announcements, Seed price & random messages players pay with Seeds to shout out.
- [ ] **Jitsi Integration?** - Add the ability to have calls directly from the interface, maybe have like a floating window when a call is happening so others see it
- [ ] **Audius Integration**
- [ ] **Dune Analytics x Dashboard**
- [ ] **dApp Xyz Integration**
